# Generated by Django 6.0.3 on 2026-03-31 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(default='MBBS', max_length=100),
            preserve_default=False,
        ),
    ]
